### ISSUE TITLE
Make errors

### ISSUE THREAD

**Issue by krak3n77** [sensepost/esp-vnc#1]
I get this error when entering the "make" command.
esp-vnc-2.2.3 montgomery$ make 
Makefile:73: Using SDK from 
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
VERSION: esp-link - 2017-07-11 14:06:43 - 8032e5e
CC mqtt/mqtt.c
/bin/sh: /Users/montgomery/Downloads/esp-open-sdk/xtensa-lx106-elf/bin/xtensa-lx106-elf-gcc: No such file or directory
make: *** [build/mqtt/mqtt.o] Error 127

**Comment by RoganDawes** [comment]
Hi,

Sorry for the delay in responding to you. It looks like you have not got the SDK installed correctly, or the xtensa compiler.

Please following the "Building the Firmware" instructions in the README.adoc file in the root of the esp-vnc directory.
